# Generated by Django 4.2.16 on 2025-10-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicineFrequency', models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Once', max_length=10)),
                ('medicineTakingType', models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('With Food', 'With Food'), ('Empty Stomach', 'Empty Stomach'), ('Anytime', 'Anytime')], default='Anytime', max_length=20)),
                ('medicineUnit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('units', 'units'), ('pill', 'pill'), ('tablet', 'tablet'), ('capsule', 'capsule'), ('drop', 'drop'), ('puff', 'puff')], default='pill', max_length=10)),
                ('medicineType', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Cream', 'Cream'), ('Lotion', 'Lotion'), ('Inhaler', 'Inhaler'), ('Drops', 'Drops'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Powder', 'Powder'), ('Gel', 'Gel'), ('Spray', 'Spray'), ('Other', 'Other')], default='Tablet', max_length=20)),
                ('medicineReminderMethod', models.CharField(choices=[('Notification', 'Notification'), ('Email', 'Email'), ('SMS', 'SMS'), ('Call', 'Call'), ('Other', 'Other')], default='Notification', max_length=15)),
                ('medicineDurationType', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Until Finished', 'Until Finished'), ('Lifetime', 'Lifetime')], default='Days', max_length=15)),
                ('medicineDosage', models.FloatField(default=1.0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('measurement_time', models.DateTimeField()),
                ('mesaurement_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L'), ('%', '%'), ('bpm', 'bpm'), ('mmHg', 'mmHg'), ('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
