# Generated by Django 4.2.16 on 2025-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='measurementlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
