# Generated by Django 4.2.16 on 2025-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_measurementlog_is_active_measurementlog_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementlog',
            name='measurement_time',
            field=models.DateTimeField(),
        ),
    ]
