# Generated by Django 4.2.16 on 2025-09-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
                ('mesaurement_value', models.FloatField()),
                ('units', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L'), ('%', '%'), ('bpm', 'bpm'), ('mmHg', 'mmHg'), ('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
