# Generated by Django 4.2.16 on 2025-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_measurementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='medicineDosage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineDurationType',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Until Finished', 'Until Finished'), ('Lifetime', 'Lifetime')], default='Days', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineFrequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Once', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineReminderMethod',
            field=models.CharField(choices=[('Notification', 'Notification'), ('Email', 'Email'), ('SMS', 'SMS'), ('Call', 'Call'), ('Other', 'Other')], default='Notification', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineTakingType',
            field=models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food'), ('With Food', 'With Food'), ('Empty Stomach', 'Empty Stomach'), ('Anytime', 'Anytime')], default='Anytime', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineType',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Cream', 'Cream'), ('Lotion', 'Lotion'), ('Inhaler', 'Inhaler'), ('Drops', 'Drops'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Powder', 'Powder'), ('Gel', 'Gel'), ('Spray', 'Spray'), ('Other', 'Other')], default='Tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='medicineUnit',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('units', 'units'), ('pill', 'pill'), ('tablet', 'tablet'), ('capsule', 'capsule'), ('drop', 'drop'), ('puff', 'puff')], default='pill', max_length=10),
        ),
    ]
